server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/ex
    username: root
    password: Admin@123
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        highlight_sql: true
        jdbc:
          batch_size: 20
          batch_versioned_data: true
        order_inserts: true
        order_updates: true
    show-sql: true
    open-in-view: false